projectName: Cybersecurity Terminology
jsonFilePath: ./input.json
baseUrl: https://gracker.ai
portalHeading: Cybersecurity Terminology Portal
portalDescription: >-
  World's first AI-driven growth engine for cybersecurity B2B SaaS. Engage
  prospects, demonstrate expertise, and fuel expansion through customized,
  data-backed content strategies.
portalTitle: AI-powered Cybersecurity Marketing Solution
searchPlaceholder: Search cybersecurity terms...
useAlphabetsCategory: true
homeLink: https://gracker.ai/
logoLink: https://gracker.ai/
ctaText: Get Started
aboutLink: https://gracker.ai/about
productsLink: https://gracker.ai/products
logoImgUrl: https://gracker.ai/_astro/logo-white.DuNP12gY_Z22gpAz.svg
ctaLink: https://portal.gracker.ai/
copyrightText: '&copy; Copyright 2024, Gracker.'
faviconUrl: https://gracker.ai/favicon.ico
googleTagManagerId: GTM-TPM6JQPC
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks:
  - platform: LinkedIn
    url: https://www.linkedin.com/company/gracker-ai/
  - platform: Twitter
    url: https://x.com/grackerAI
  - platform: Instagram
    url: https://www.instagram.com/grackerai/
theme:
  primaryColor: '#ffffff'
  secondaryColor: '#000000'
  backgroundColor: '#f8f9fa'
  textColor: '#212529'
  accentColor: '#007bff'
fonts:
  - family: Bricolage Grotesque
    weights:
      - 400
      - 500
      - 600
  - family: Poppins
    weights:
      - 400
      - 500
      - 600
